### ISSUE TITLE
View Card links broken

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#43]
Lead to "page not found". @meganmckissack can you provide some background on the original intent of the "View Card" link - maybe post the link to the spec from Product?

![image](https://user-images.githubusercontent.com/2536801/26837937-90115b6e-4a93-11e7-8036-4ea19f22d0b5.png)

**Comment by outerpress** [comment]
Assigning to @meganmckissack to push to the platform team

**Comment by meganmckissack** [comment]
@outerpress From my understanding, it's supposed to take you to a single page card view that has context and data sources information.  This wasn't really communicated well and I don't think anyone got that far before demo day to give you an example but here's a screenshot and a link to the [style guide](https://drive.google.com/open?id=0Byy4RAOeNM0yOWpnNFdnSURhekE).  

![civic platform info civic style guide v1 0 pdf at master hackoregon civic platform info](https://user-images.githubusercontent.com/2355543/27358063-bb702ac4-55c9-11e7-9135-dbebf7e0cff9.png)

**Comment by outerpress** [comment]
Thanks @meganmckissack, that does sound familiar now. I'll add details to this issue about which pages to create and the content that will go in them.

**Comment by clemf** [comment]
Closed because it's a platform issue.
