### ISSUE TITLE
View/Share Card links - extra spacing before text

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#44]
The underline sticks out to the left of the text. Should be aligned to under it.

![image](https://user-images.githubusercontent.com/2536801/26837956-a43a14e6-4a93-11e7-9de3-b5e914c93c2e.png)

**Comment by outerpress** [comment]
Assigning to @meganmckissack to push to Platform

**Comment by clemf** [comment]
This should be moved to https://github.com/hackoregon/component-library/issues

**Comment by clemf** [comment]
Moved to [component-library](https://github.com/hackoregon/component-library/issues/79)

**Comment by flamingveggies** [comment]
The space is because of the missing glyphicons. It probably should be fixed at the platform level, but I know budget did a fix in their repo to get them working.
