### ISSUE TITLE
Improve body text readability

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#49]
Two issues - the body text color is too light, and the line height to text ratio is to tight.

Recommended body text: #614861
Recommended line height ratio: 1.6

![image](https://user-images.githubusercontent.com/2536801/26884690-39419fc0-4b55-11e7-9025-506872cbd2ae.png)

**Comment by outerpress** [comment]
Assigning to @meganmckissack to push to the Platform team

**Comment by clemf** [comment]
Ok, I made these changes. I tried to make all the body text styles consistent, let me know if I missed anything. There is not more differentiation between body text and footnote text. I can improve the footnote text when you provide the mockup.
