### ISSUE TITLE
Questions: Platform vs. Collection styles

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#53]
I'm writing bugs that would affect the styling of the overall platform if implemented. Questions:

* Who owns the Platform-level styles?
* Where do the Platform-level styles end, and the Collection-level styles begin?

@meganmckissack @AndoRando @clemf any insights?

**Comment by meganmckissack** [comment]
I believe Ven, Adrienne, and Jen own the platform level styles.

Where they differentiate is a bit tough, if we used the react storybook components and they were all up to date, the headers, story card styles, footers, and some others would be controlled globally.  

The platform style guide covers fonts and colors but not media queries or grids systems and etc.  
https://drive.google.com/file/d/0Byy4RAOeNM0yOWpnNFdnSURhekE/view?usp=sharing

**Comment by clemf** [comment]
That's a bit out of my wheelhouse I'm afraid. Maybe @DavideDaniel could weigh in?

**Comment by outerpress** [comment]
Thanks all! I'm going to assign anything that seems platform-specific to you @meganmckissack - if they're actually Homelessness-specific, push them back to me and I'll get them to the right spot.
