### ISSUE TITLE
H2 - Prep for 2017 data

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#54]
We need the APIs fully hooked up and ready for the city to push 2017 data for H2 - Population

**Comment by MikeTheCanuck** [comment]
What does this mean - which APIs are not hooked up, which APIs are not ready?

Not that I can likely help much here, but on the off-chance I can contribute...

**Comment by outerpress** [comment]
This is a very good question! I'm filing it in a separate issue :)

**Comment by outerpress** [comment]
@MikeTheCanuck @clemf answered the question of what APIs need to be hooked up in: https://github.com/hackoregon/teamHomelessness-frontend/issues/57

Since this one was hooked up, I'm closing this issue. (It will need some content updates to handle multi-year data, I'll be adding those in a separate issue).
